name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *"   # раз в сутки (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Generate 3D contributions SVGs
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push generated images (if any)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          if git commit -m "docs: generate profile-3d images" -a; then
            git push
          else
            echo "No changes to commit"
          fi
